---
- hosts: aws
  remote_user: centos
  
  tasks:
      - name: update
        command: sudo yum update -y
      - name: set up repo
        command: "sudo yum install -y yum-utils \ device-mapper-persistent-data \ lvm2"
      - name: find docker-ce version stable
        command: "sudo yum-config-manager \ --add-repo \ https://download.docker.com/linux/centos/docker-ce.repo"
      - name: install docker-ce from repo
        command: sudo yum install docker-ce -y
      - name: start docker
        command: sudo systemctl start docker
      - name: enable docker
        command: sudo systemctl enable docker
      - name: add permission of user
        command: sudo usermod -aG docker centos
      - name: install docker compose
        command: sudo curl -L https://github.com/docker/compose/releases/download/1.11.2/docker-compose-Linux-x86_64 -o /usr/local/bin/docker-compose
      - name: add permission of docker compose
        command: sudo chmod +x /usr/local/bin/docker-compose
